---
- name: Ansible Playbook 1
  hosts: localhost
  connection: local
  tasks:

    - name: shell
      shell: oc login -u "{{ openshift_admin_user }}" -p "{{ openshift_admin_password }}" "{{ openshift_host }}"  

    - name: Create my first VM
      kubevirt.core.kubevirt_vm:
        namespace: vmexamples
        name: vm1
        cpu_cores: 1
        memory: 4Gi
        disks:
          - name: containerdisk
            volume:
              containerDisk:
                image: kubevirt/cirros-container-disk-demo:latest
            disk:
              bus: virtio
