---
version: 1
build_arg_defaults:
  ANSIBLE_GALAXY_CLI_COLLECTION_OPTS: "-c"
  EE_BASE_IMAGE: 'aaphub001.lnx.example.local/ee-supported-rhel8:latest'
  EE_BUILDER_IMAGE: 'aaphub001.lnx.example.local/ansible-builder-rhel8:latest'
ansible_config: 'ansible.cfg'

dependencies:
  galaxy: requirements.yml
  python: requirements.txt
  system: bindep.txt

additional_build_steps:
  prepend: |
    RUN cat /etc/os-release
    VOLUME ["/repository"]
  append:
    - RUN echo This is a post-install command!
    - RUN microdnf install -y crypto-policies-scripts
    - RUN update-crypto-policies --set DEFAULT:AD-SUPPORT
    - RUN pip3 install requests

